# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usedactivationkeys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='usedactivationkeys',
            name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='yearofbirth',
            new_name='year_of_birth',
        ),
        migrations.DeleteModel(
            name='UsedActivationKeys',
        ),
    ]
