# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0002_zipcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartwrapper',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chart',
            name='geotable',
            field=models.CharField(choices=[('pollster_zip_codes', 'zip level')], default='pollster_zip_codes', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart',
            name='sqlfilter',
            field=models.CharField(choices=[('NONE', 'None'), ('USER', 'Current User'), ('PERSON', 'Current Person')], default='NONE', max_length=255, verbose_name='Results Filter'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='sqlsource',
            field=models.TextField(blank=True, default='', verbose_name='SQL Source Query'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='option',
            name='group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, default='', max_length=4095),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='virtual_inf',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='virtual_regex',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='virtual_sup',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='regex',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('builtin', 'Builtin'), ('text', 'Open Answer'), ('single-choice', 'Single Choice'), ('multiple-choice', 'Multiple Choice'), ('matrix-select', 'Matrix Select'), ('matrix-entry', 'Matrix Entry')], max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='visual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questioncolumn',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questiondatatype',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionrow',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruletype',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shortname',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='DRAFT', help_text='Use full editor to publish and unpublish', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='survey',
            name='version',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationoption',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translationoption',
            name='text',
            field=models.CharField(blank=True, default='', max_length=4095),
        ),
        migrations.AlterField(
            model_name='translationquestion',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translationquestion',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translationquestion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationquestioncolumn',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationquestionrow',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationsurvey',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=255),
        ),
        migrations.AlterField(
            model_name='translationsurvey',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='virtualoptiontype',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
