# Generated by Django 2.2.16 on 2020-11-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0004_auto_20201020_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='data_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shortname',
            field=models.SlugField(default='', max_length=28),
        ),
        migrations.AlterField(
            model_name='survey',
            name='version',
            field=models.SlugField(blank=True, default='', max_length=2),
        ),
    ]
