# Generated by Django 2.2.16 on 2021-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0006_survey_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveygroup',
            name='from_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='surveygroup',
            name='to_joined',
            field=models.DateField(null=True),
        ),
    ]
