# Generated by Django 2.2.16 on 2020-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0007_survey_group_date_joined_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('builtin', 'Builtin'), ('text', 'Open Answer'), ('single-choice', 'Single Choice'), ('multiple-choice', 'Multiple Choice'), ('matrix-select', 'Matrix Select'), ('matrix-entry', 'Matrix Entry'), ('matrix-check', 'Matrix Check')], max_length=255),
        ),
    ]
