# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_userreminderinfo_user_as_onetoone_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindersettings',
            name='batch_size',
            field=models.IntegerField(blank=True, help_text=b"Batch size determines the max. sent emails per call to 'reminder_send'; choose in coordinance with your crontab interval and total users; Leave empty to not have any maximum", null=True, verbose_name=b'Batch size'),
        ),
    ]
