# Generated by Django 2.2.16 on 2020-10-20 08:40

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20201006_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettertemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newslettertemplatetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'news letter template Translation'},
        ),
        migrations.AlterModelOptions(
            name='newslettertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'news letter Translation'},
        ),
        migrations.AlterModelManagers(
            name='newsletter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='newslettertemplate',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='newslettertemplatetranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='newslettertemplatetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='reminder.NewsLetterTemplate'),
        ),
        migrations.AlterField(
            model_name='newslettertranslation',
            name='language_code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='newslettertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='reminder.NewsLetter'),
        ),
    ]
