# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='surveyresposedraft',
            index_together=set([('global_id', 'survey_id')]),
        ),
    ]
