# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresposedraft_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyidcode',
            name='surveyuser_global_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser', to_field='global_id'),
        ),
    ]
