# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 14:15
from __future__ import unicode_literals
from datetime import datetime
import logging

from django.db import migrations, models
import django.db.models.deletion

logger = logging.getLogger(__name__)


def migrate_drafts(apps, schema_editor):
    OldDraftModel = apps.get_model("survey", "SurveyResposeDraft")
    NewDraftModel = apps.get_model("survey", "SurveyResponseDraft")
    SurveyUser = apps.get_model("survey", "SurveyUser")
    Survey = apps.get_model("pollster", "Survey")

    existing_surveys = Survey.objects.values_list('id', flat=True)

    logger.info('Migrating existing survey drafts')

    for draft in OldDraftModel.objects.all():
        if draft.survey_id not in existing_surveys:
            logger.info('Draft is referencing missing survey. Skipping.')
            continue

        # During migrations the SurveyUser.DoesNotExist does not work, so we
        # check for existence by getting a queryset and use .exists()
        survey_user_queryset = SurveyUser.objects.filter(
            global_id=draft.global_id)

        if not survey_user_queryset.exists():
            logger.info('Draft is referencing missing user. Skipping.')
            continue

        NewDraftModel.objects.create(
            survey_id=draft.survey_id,
            survey_user=survey_user_queryset.first(),
            timestamp=datetime.fromtimestamp(draft.timestamp),
            form_data=draft.form_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0002_zipcodes'),
        ('survey', '0003_surveyuser_global_id_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponseDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('form_data', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollster.Survey')),
                ('survey_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser')),
            ],
        ),
        migrations.RunPython(migrate_drafts, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SurveyResposeDraft',
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponsedraft',
            unique_together=set([('survey_user', 'survey')]),
        ),
        migrations.AlterIndexTogether(
            name='surveyresponsedraft',
            index_together=set([('survey_user', 'survey')]),
        ),
    ]
