# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollster', '0002_zipcodes'),
        ('survey', '0003_surveyuser_global_id_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponseDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('form_data', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollster.Survey')),
                ('survey_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser')),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyResposeDraft',
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponsedraft',
            unique_together=set([('survey_user', 'survey')]),
        ),
        migrations.AlterIndexTogether(
            name='surveyresponsedraft',
            index_together=set([('survey_user', 'survey')]),
        ),
    ]
