# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyresponsedraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastresponse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser'),
        ),
        migrations.AlterField(
            model_name='localprofile',
            name='surveyuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyUser'),
        ),
    ]
